// src/pages/Login.jsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";

export default function Login() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const handleSubmit = async (event) => {
    event.preventDefault();
    navigate('/admin');
    // Handle the login logic here
  };
  return (
    <>
      <div className=" px-6  lg:px-8">
        <div className="sm:mx-auto sm:w-full sm:max-w-sm">
          <img
            alt="Your Company"
            src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=600"
            className="mx-auto h-10 w-auto"
          />
          <h2 className="text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">
            Sign in to your account
          </h2>
        </div>

        <div className=" sm:mx-auto sm:w-full sm:max-w-sm">
          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <label
                htmlFor="email"
                className="block text-sm font-medium leading-6 text-gray-900"
              >
                Email address
              </label>
              <div className="mt-2">
                <input
                 value={username} onChange={(e) => setUsername(e.target.value)}
                  id="email"
                  name="email"
                  type="email"
                  required
                  autoComplete="email"
                  className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                />
              </div>
            </div>

            <div>
              <div className="flex items-center justify-between">
                <label
                  htmlFor="password"
                  className="block text-sm font-medium leading-6 text-gray-900"
                >
                  Password
                </label>
                <div className="text-sm">
                  <a
                    href="#"
                    className="font-semibold text-indigo-600 hover:text-indigo-500"
                  >
                    Forgot password?
                  </a>
                </div>
              </div>
              <div className="mt-2">
                <input
                value={password} onChange={(e) => setPassword(e.target.value)} 
                  id="password"
                  name="password"
                  type="password"
                  required
                  autoComplete="current-password"
                  className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                />
              </div>
            </div>

            <div>
              <button 
                type="submit"
                className="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                Sign in
              </button>
            </div>
          </form>
        </div>
      </div>
    </>
  );
}

// src/app/pages/login/login.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  imports: [CommonModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
  private readonly authService = inject(AuthService);
  private readonly router = inject(Router);

  username = '';
  password = '';
  showPassword = signal(false);
  errorMessage = signal('');
  isLoading = signal(false);

  onSubmit(): void {
    this.errorMessage.set('');
    this.isLoading.set(true);

    // Small delay for UX feel
    setTimeout(() => {
      const error = this.authService.login(this.username, this.password);
      this.isLoading.set(false);

      if (error) {
        this.errorMessage.set(error);
      } else {
        this.router.navigate(['/home']);
      }
    }, 600);
  }

  togglePassword(): void {
    this.showPassword.update(v => !v);
  }
}

<div class="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-slate-950 transition-colors">
  <div class="py-6 px-4 w-full">
    <div class="grid lg:grid-cols-2 items-center gap-6 max-w-6xl w-full mx-auto">

      <!-- Form Card -->
      <div class="border border-slate-300 dark:border-slate-700 rounded-2xl p-6 sm:p-8 max-w-md
                  shadow-[0_2px_22px_-4px_rgba(93,96,127,0.2)] dark:shadow-black/40
                  max-lg:mx-auto lg:order-2 bg-white dark:bg-slate-900">
        <form (ngSubmit)="onSubmit()" class="space-y-6">

          <!-- Header -->
          <div class="mb-6">
            <div class="flex items-center gap-2 mb-3">
              <span class="material-symbols-outlined text-accent text-3xl" style="font-variation-settings: 'FILL' 1;">
                school
              </span>
              <span class="text-xl font-bold text-accent">Resources</span>
            </div>
            <h1 class="text-slate-900 dark:text-white text-3xl font-semibold">Welcome back</h1>
            <p class="text-slate-600 dark:text-gray-400 text-[15px] mt-1 leading-relaxed">
              Sign in to access your preparation resources, blogs, and tools.
            </p>
          </div>

          <!-- Error Message -->
          @if (errorMessage()) {
            <div class="p-3 rounded-xl bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800
                        flex items-center gap-2 animate-shake">
              <span class="material-symbols-outlined text-red-500 text-lg">error</span>
              <span class="text-sm text-red-700 dark:text-red-400">{{ errorMessage() }}</span>
            </div>
          }

          <!-- Username -->
          <div>
            <label class="text-slate-900 dark:text-gray-200 text-sm font-medium mb-2 block">Username</label>
            <div class="relative flex items-center">
              <span class="material-symbols-outlined absolute left-3 text-gray-400 text-xl">person</span>
              <input [(ngModel)]="username" name="username" type="text" required autocomplete="username"
                     class="w-full text-sm text-slate-900 dark:text-white bg-white dark:bg-slate-800
                            border border-slate-300 dark:border-slate-600 pl-10 pr-4 py-3 rounded-xl
                            outline-none focus:ring-2 focus:ring-accent/50 focus:border-accent transition-all"
                     placeholder="Enter username" />
            </div>
          </div>

          <!-- Password -->
          <div>
            <label class="text-slate-900 dark:text-gray-200 text-sm font-medium mb-2 block">Password</label>
            <div class="relative flex items-center">
              <span class="material-symbols-outlined absolute left-3 text-gray-400 text-xl">lock</span>
              <input [(ngModel)]="password" name="password" [type]="showPassword() ? 'text' : 'password'"
                     required autocomplete="current-password"
                     class="w-full text-sm text-slate-900 dark:text-white bg-white dark:bg-slate-800
                            border border-slate-300 dark:border-slate-600 pl-10 pr-12 py-3 rounded-xl
                            outline-none focus:ring-2 focus:ring-accent/50 focus:border-accent transition-all"
                     placeholder="Enter password" />
              <button type="button" (click)="togglePassword()"
                      class="absolute right-3 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition-colors">
                <span class="material-symbols-outlined text-xl">
                  {{ showPassword() ? 'visibility_off' : 'visibility' }}
                </span>
              </button>
            </div>
          </div>

          <!-- Remember Me -->
          <div class="flex flex-wrap items-center justify-between gap-4">
            <div class="flex items-center">
              <input id="remember-me" name="remember-me" type="checkbox"
                     class="h-4 w-4 shrink-0 text-accent focus:ring-accent
                            border-slate-300 dark:border-slate-600 rounded dark:bg-slate-800" />
              <label for="remember-me" class="ml-2 block text-sm text-slate-700 dark:text-gray-300">
                Remember me
              </label>
            </div>
          </div>

          <!-- Submit -->
          <div class="!mt-8">
            <button type="submit"
                    [disabled]="isLoading() || !username.trim() || !password.trim()"
                    class="w-full py-3 px-4 text-[15px] font-medium tracking-wide rounded-xl text-white
                           btn-accent shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2
                           disabled:opacity-60 disabled:cursor-not-allowed">
              @if (isLoading()) {
                <svg class="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path>
                </svg>
                Signing in...
              } @else {
                <span class="material-symbols-outlined text-lg">login</span>
                Sign in
              }
            </button>
          </div>
        </form>
      </div>

      <!-- Illustration -->
      <div class="max-lg:mt-8 lg:order-1">
        <img src="assets/signin.svg" class="w-full mx-auto block object-cover" alt="login illustration" />
      </div>
    </div>
  </div>
</div>
